In [10]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

year = 2022
table_label = 'games'
url = f'https://www.pro-football-reference.com/teams/sea/{year}.htm#{table_label}'
# print(url)
response = requests.get(url=url)
soup = BeautifulSoup(response.content, features="lxml")
# print(soup.findAll('tr')[1])
# print(soup.findAll('tr')[7].findAll('th'))
headers = [th.getText() for th in soup.findAll('tr')[7].findAll('th')]
print(headers)
headers = headers[1:]
print(headers)

rows = soup.findAll('tr', class_ = lambda table_rows: table_rows != "thead")
team_results = [[td.getText() for td in rows[i].findAll('td')] for i in range(8,26)]
# print(team_results)

seahawks_data = pd.DataFrame(team_results, columns=headers)
seahawks_data.head()

['Week', 'Day', 'Date', '', '', '', 'OT', 'Rec', '', 'Opp', 'Tm', 'Opp', '1stD', 'TotYd', 'PassY', 'RushY', 'TO', '1stD', 'TotYd', 'PassY', 'RushY', 'TO', 'Offense', 'Defense', 'Sp. Tms']
['Day', 'Date', '', '', '', 'OT', 'Rec', '', 'Opp', 'Tm', 'Opp', '1stD', 'TotYd', 'PassY', 'RushY', 'TO', '1stD', 'TotYd', 'PassY', 'RushY', 'TO', 'Offense', 'Defense', 'Sp. Tms']

,Day,Date,,,,OT,Rec,,Opp,Tm,...,RushY,TO,1stD,TotYd,PassY,RushY,TO,Offense,Defense,Sp. Tms
0,Mon,September 12,8:20PM ET,boxscore,W,,1-0,,Denver Broncos,17,...,76,1,20,433,330,103,2,4.10,-9.94,6.84
1,Sun,September 18,4:05PM ET,boxscore,L,,1-1,@,San Francisco 49ers,7,...,36,3,25,373,184,189,,-9.18,-16.39,7.67
2,Sun,September 25,4:25PM ET,boxscore,L,,1-2,,Atlanta Falcons,23,...,112,1,24,386,207,179,2,15.09,-20.84,-1.20
3,Sun,October 2,1:00PM ET,boxscore,W,,2-2,@,Detroit Lions,48,...,235,1,27,520,375,145,2,32.93,-22.12,-3.99
4,Sun,October 9,1:00PM ET,boxscore,L,,2-3,@,New Orleans Saints,32,...,151,1,26,438,203,235,2,4.57,-15.05,0.32

In [11]:
url = f'https://www.pro-football-reference.com/players/L/LawrTr00/gamelog/2022/'
response = requests.get(url=url)
soup = BeautifulSoup(response.content, features="lxml")
headers = [th.getText() for th in soup.findAll('tr')[1].findAll('th')]
# print(headers)
headers = headers[1:]
rows = soup.findAll('tr', class_ = lambda table_rows: table_rows != "thead")
player_stats = [[td.getText() for td in rows[i].findAll('td')] for i in range(2,19)]
# print(player_stats)
player_data = pd.DataFrame(player_stats, columns=headers)

In [3]:
import pandas as pd

temp = {'a':[1,2,3], 'b':[4,5,6], 'c':[7,8,9]}
df = pd.DataFrame(data=temp, index=['A','B','C'])
print(df)
df.index.name = 'Row'
# print(df)
#want to now try the melting process
melted = pd.melt(df, var_name='Column', value_name='Value', ignore_index=False)
# print(melted)
#if you uncomment the print statements, you'll see that this mimics the example
#shown on the course website --> we can apply this process to our own datasets,
#but we need to figure out how we need to structure the data
print(melted)

   a  b  c
A  1  4  7
B  2  5  8
C  3  6  9
    Column  Value
Row
A        a      1
B        a      2
C        a      3
A        b      4
B        b      5
C        b      6
A        c      7
B        c      8
C        c      9

In [17]:
# import geopy.distance
# def calculate_distance(team1 : str, team2 : str) -> float:
#     coordinates = {
#         "Arizona Cardinals" : (33.5279053111993, -112.26248802923699),
#         "Atlanta Falcons" : (33.75658104611166, -84.4012431938295),
#         "Baltimore Ravens" : (39.278055986939314, -76.62271129536873),
#         "Buffalo Bills" : (42.77406838630884, -78.78686792299308),
#         "Carolina Panthers" : (35.225894591145675, -80.85296123497584),
#         "Chicago Bears" : (41.862433355130726, -87.61668018093484),
#         "Cincinnati Bengals" : (39.09558815127463, -84.51609417697091),
#         "Cleveland Browns" : (41.50612431804717, -81.69956546223561),
#         "Dallas Cowboys" : (32.747394617747304, -97.09449118126838),
#         "Denver Broncos" : (39.74397867677901, -105.02009065354534),
#         "Detroit Lions" : (42.340040741565296, -83.04558433621338),
#         "Green Bay Packers" : (44.501421493860505, -88.0622361676567),
#         "Houston Texans" : (29.684780528466597, -95.41076891897495),
#         "Indianapolis Colts" : (39.76016855021095, -86.16385742101808),
#         "Jacksonville Jaguars" : (30.32402341109306, -81.63738223023354),
#         "Kansas City Chiefs" : (39.049006132734625, -94.48390946991661),
#         "Las Vegas Raiders" : (36.090922613634746, -115.1832957717522),
#         "Los Angeles Chargers" : (33.953519638164856, -118.33854176452057),
#         "Los Angeles Rams" : (33.953519638164856, -118.33854176452057),
#         "Miami Dolphins" : (25.958414687460127, -80.2386036040462),
#         "Minnesota Vikings" : (44.973707804914966, -93.25744996631974),
#         "New England Patriots" : (42.09099582857695, -71.26437365223678),
#         "New Orleans Saints" : (29.951113428255248, -90.08144686349743),
#         "New York Giants" : (40.81357230213098, -74.07450097583455),
#         "New York Jets" : (40.81357230213098, -74.07450097583455),
#         "Philadelphia Eagles" : (39.90141485982268, -75.16749146746251),
#         "Pittsburgh Steelers" : (40.44679727974751, -80.01581448820603),
#         "San Francisco 49ers" : (37.40337855622536, -121.96939160572268),
#         "Seattle Seahawks" : (47.595148229165446, -122.33209920631144),
#         "Tampa Bay Buccaneers" : (27.975937833578584, -82.50335871624291),
#         "Tennessee Titans" : (36.16659318662702, -86.77130368128294),
#         "Washington Commanders" : (38.907777053902784, -76.86463498137742)
#     }
#     coord1 = coordinates[team1]
#     coord2 = coordinates[team2]
#     return geopy.distance.geodesic(coord1, coord2).miles

# test = calculate_distance("Chicago Bears", "Green Bay Packers")
# print(test)

183.5590644222687